# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='teaser',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
