# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 06:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('preface_description', models.TextField(blank=True, help_text='Preface yourself')),
                ('main_description', models.TextField(blank=True, help_text='About me')),
                ('skill_name', models.CharField(blank=True, max_length=255)),
                ('skill_percent', models.PositiveSmallIntegerField(blank=True)),
                ('education', models.CharField(blank=True, help_text='Education name', max_length=255)),
                ('education_description', models.TextField(blank=True, help_text='Describe education')),
                ('image', models.ImageField(blank=True, upload_to='photo', verbose_name='Photo')),
            ],
        ),
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(unique=True)),
                ('benefit_description', models.TextField(blank=True, help_text='Description')),
                ('image', models.ImageField(blank=True, upload_to='benefit', verbose_name='Benefit picture')),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('fee_description', models.TextField(blank=True, help_text='Fee Description')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price', max_digits=15)),
                ('discount', models.DecimalField(decimal_places=2, help_text='Discount', max_digits=15, null=True)),
                ('increase', models.DecimalField(decimal_places=2, help_text='Increase', max_digits=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('goal_description', models.TextField(blank=True, help_text='Description')),
                ('image', models.ImageField(blank=True, upload_to='picture', verbose_name='Goal picture')),
            ],
        ),
        migrations.CreateModel(
            name='Preface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True, help_text='Preface project')),
                ('image', models.ImageField(blank=True, upload_to='preface_pic', verbose_name='Preface Image')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(unique=True)),
                ('avatar', models.ImageField(blank=True, upload_to='photo_ava', verbose_name='Photo')),
                ('position', models.TextField(blank=True, help_text='Position')),
                ('testimonial', models.TextField(blank=True, help_text='Testimonial')),
                ('location', models.CharField(help_text='Location', max_length=250)),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
