# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(blank=True, max_length=255)),
                ('skill_percent', models.PositiveSmallIntegerField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='about',
            name='skill_name',
        ),
        migrations.RemoveField(
            model_name='about',
            name='skill_percent',
        ),
        migrations.AddField(
            model_name='about',
            name='skills',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Skill'),
            preserve_default=False,
        ),
    ]
