# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 13:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20161004_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benefit',
            name='slug',
        ),
    ]
