# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_benefit_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='increase_description',
            field=models.TextField(blank=True, help_text='Increase Description'),
        ),
    ]
