# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_fee_discount_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('preface', models.TextField(blank=True, help_text='Main idea')),
                ('definition', models.CharField(blank=True, help_text='Definition', max_length=80)),
                ('fb', models.URLField(blank=True, help_text='Facebook link')),
                ('tw', models.URLField(blank=True, help_text='Twitter link')),
                ('gg', models.URLField(blank=True, help_text='Google plus link')),
                ('ig', models.URLField(blank=True, help_text='Instagramm link')),
                ('ml', models.URLField(blank=True, help_text='Email')),
            ],
        ),
    ]
