# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='definition',
            field=models.TextField(blank=True, help_text='Definition'),
        ),
    ]
